# Generated by Django 4.2.19 on 2025-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_product_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marketplace_sku', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=255)),
                ('im_sku', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('marketplace', models.CharField(max_length=255)),
                ('level_1', models.CharField(max_length=255)),
                ('linworks_title', models.TextField()),
                ('parent_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'new_product_mapping',
            },
        ),
        migrations.CreateModel(
            name='product_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marketplace_sku', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=255)),
                ('im_sku', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('marketplace', models.CharField(max_length=255)),
                ('level_1', models.CharField(max_length=255)),
                ('linworks_title', models.TextField()),
                ('parent_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_mapping',
            },
        ),
    ]
