# Generated by Django 4.2.19 on 2025-02-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_new_product_mapping_product_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_mapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product_mapping',
            name='updated_at',
        ),
    ]
