# Generated by Django 4.2.19 on 2025-02-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_mapping_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_mapping',
            name='comment',
        ),
    ]
