# Generated by Django 4.2.19 on 2025-02-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_mapping_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_mapping',
            name='parent_sku',
        ),
    ]
