# Generated by Django 4.2.19 on 2025-02-18 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_mapping_parent_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mapping',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='parent_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
