# Generated by Django 4.2.19 on 2025-02-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_mapping_comment_product_mapping_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_product_mapping',
            name='parent_sku',
        ),
        migrations.RemoveField(
            model_name='product_mapping',
            name='parent_sku',
        ),
    ]
