# Generated by Django 4.2.19 on 2025-02-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_new_product_mapping_parent_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_product_mapping',
            old_name='marketplace',
            new_name='sales_channel',
        ),
        migrations.RenameField(
            model_name='product_mapping',
            old_name='marketplace',
            new_name='sales_channel',
        ),
    ]
