# Generated by Django 4.2.19 on 2025-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_marketplace_new_product_mapping_sales_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_mapping',
            name='level_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_mapping',
            name='linworks_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mapping',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_mapping',
            name='sales_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
