# Generated by Django 4.2.19 on 2025-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_mapping_level_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_mapping',
            name='im_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
