# Generated by Django 4.2.19 on 2025-02-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_mapping_im_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_product_mapping',
            old_name='modified_by',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='new_product_mapping',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='new_product_mapping',
            name='linworks_title',
        ),
        migrations.RemoveField(
            model_name='new_product_mapping',
            name='sales_channel',
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='channel',
            field=models.CharField(default='Amazon', max_length=255),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='level_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='level_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='level_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='level_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='marketplace',
            field=models.CharField(default='Amazon', max_length=255),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='marketplace_sales_table',
            field=models.CharField(default='stg_tr_amazon_raw', max_length=255),
        ),
        migrations.AlterField(
            model_name='new_product_mapping',
            name='marketplace_sku',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
