# Generated by Django 4.2.19 on 2025-02-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_modified_by_new_product_mapping_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_product_mapping',
            name='im_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
