# Generated by Django 4.2.19 on 2025-02-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_new_product_mapping_im_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_product_mapping',
            name='level_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
