# Generated by Django 4.2.19 on 2025-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_new_product_mapping_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mapping',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
