# Generated by Django 4.2.19 on 2025-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_mapping_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mapping',
            name='amazonn_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
