# Generated by Django 4.2.19 on 2025-03-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_mapping_amazonn_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_mapping',
            old_name='amazonn_title',
            new_name='amazon_title',
        ),
    ]
