# Generated by Django 4.2.19 on 2025-04-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_amazonn_title_product_mapping_amazon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_product_mapping',
            name='linworks_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
