# Generated by Django 4.2.19 on 2025-04-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_new_product_mapping_linworks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_product_mapping',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='comment_by_finance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='modified_by_admin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='modified_by_finance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_product_mapping',
            name='parent_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='comment_by_finance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='modified_by_admin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='modified_by_finance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='parent_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('SCM', 'Supply Chain Management'), ('FINANCE', 'Finance Department'), ('ADMIN', 'Administrator')], default='SCM', max_length=10),
        ),
    ]
