# Generated by Django 4.2.21 on 2025-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_new_product_mapping_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_product_mapping',
            name='marketplace_sku',
            field=models.CharField(max_length=255),
        ),
    ]
