# Generated by Django 4.2.19 on 2025-08-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_new_product_mapping_marketplace_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('SCM', 'Supply Chain Management'), ('FINANCE', 'Finance Department'), ('ADMIN', 'Administrator'), ('READ_ONLY', 'Read Only')], default='SCM', max_length=10),
        ),
    ]
